package com.alexandrupanait.cpdlc_simulator.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

@Entity
@Table(name = "cpdlc_session")
public class CpdlcSession {
    
    @OneToMany(mappedBy = "session")
    private List<CpdlcMessage> messages = new ArrayList<>();


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // to be generated by the database
    private Long id;
    private String callsign;
    private String status;
    private LocalDateTime startedAt;
    private LocalDateTime closedAt;

    // Constructor
    public CpdlcSession(Long id, String callsign, String status, LocalDateTime startedAt, LocalDateTime closedAt){
        this.id =id;
        this.callsign = callsign;
        this.status = status;
        this.startedAt = startedAt;
        this.closedAt = closedAt;

    }
    public CpdlcSession() {
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getCallsign() {
        return callsign;
    }   
    public void setCallsign(String callsign) {
        this.callsign = callsign;
    }
    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }
    public LocalDateTime getStartedAt() {
        return startedAt;
    }
    public void setStartedAt(LocalDateTime startedAt) {
        this.startedAt = startedAt;
    }
    public LocalDateTime getClosedAt() {
        return closedAt;
    }
    public void setClosedAt(LocalDateTime closedAt) {
        this.closedAt = closedAt;
    }


}
